/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapPktHdr */

#ifndef _Included_org_jnetpcap_PcapPktHdr
#define _Included_org_jnetpcap_PcapPktHdr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_PcapPktHdr
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapPktHdr_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
