/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapBpfProgram */

#ifndef _Included_org_jnetpcap_PcapBpfProgram
#define _Included_org_jnetpcap_PcapBpfProgram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_PcapBpfProgram
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapBpfProgram_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_PcapBpfProgram
 * Method:    initPeer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapBpfProgram_initPeer
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_PcapBpfProgram
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapBpfProgram_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_PcapBpfProgram
 * Method:    initFromBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapBpfProgram_initFromBuffer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jnetpcap_PcapBpfProgram
 * Method:    getInstructionCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_PcapBpfProgram_getInstructionCount
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_PcapBpfProgram
 * Method:    getInstruction
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_PcapBpfProgram_getInstruction
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
