/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JScannerReference */

#ifndef _Included_org_jnetpcap_packet_JScannerReference
#define _Included_org_jnetpcap_packet_JScannerReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_packet_JScannerReference
 * Method:    disposeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JScannerReference_disposeNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
