/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JScanner */

#ifndef _Included_org_jnetpcap_packet_JScanner
#define _Included_org_jnetpcap_packet_JScanner
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JScanner_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JScanner_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_packet_JScanner_DEFAULT_BLOCKSIZE
#define org_jnetpcap_packet_JScanner_DEFAULT_BLOCKSIZE 102400L
#undef org_jnetpcap_packet_JScanner_MAX_ENTRY_COUNT
#define org_jnetpcap_packet_JScanner_MAX_ENTRY_COUNT 64L
#undef org_jnetpcap_packet_JScanner_MAX_ID_COUNT
#define org_jnetpcap_packet_JScanner_MAX_ID_COUNT 64L
/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JScanner_initIds
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JScanner_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    getFrameNumber
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_packet_JScanner_getFrameNumber
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    init
 * Signature: (Lorg/jnetpcap/packet/JScan;)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JScanner_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    loadFlags
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JScanner_loadFlags
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    loadScanners
 * Signature: ([Lorg/jnetpcap/packet/JHeaderScanner;)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JScanner_loadScanners
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    scan
 * Signature: (Lorg/jnetpcap/packet/JPacket;Lorg/jnetpcap/packet/JPacket/State;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JScanner_scan
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_packet_JScanner
 * Method:    setFrameNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JScanner_setFrameNumber
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
