/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_format_JFormatter */

#ifndef _Included_org_jnetpcap_packet_format_JFormatter
#define _Included_org_jnetpcap_packet_format_JFormatter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
