/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_HoldQueue */

#ifndef _Included_org_jnetpcap_util_HoldQueue
#define _Included_org_jnetpcap_util_HoldQueue
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_util_HoldQueue_MAX_ARRAY_SIZE
#define org_jnetpcap_util_HoldQueue_MAX_ARRAY_SIZE 2147483639L
#ifdef __cplusplus
}
#endif
#endif
