/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_winpcap_WinPcapStat */

#ifndef _Included_org_jnetpcap_winpcap_WinPcapStat
#define _Included_org_jnetpcap_winpcap_WinPcapStat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_winpcap_WinPcapStat
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_winpcap_WinPcapStat_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
