/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapInteger */

#ifndef _Included_org_jnetpcap_PcapInteger
#define _Included_org_jnetpcap_PcapInteger
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
