/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_checksum_Checksum */

#ifndef _Included_org_jnetpcap_util_checksum_Checksum
#define _Included_org_jnetpcap_util_checksum_Checksum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc16CCITT
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc16CCITT
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc16CCITTSeed
 * Signature: (Lorg/jnetpcap/nio/JBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc16CCITTSeed
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc16X25CCITT
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc16X25CCITT
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc32c
 * Signature: (Lorg/jnetpcap/nio/JBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc32c
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc32CCITT
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc32CCITT
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc32CCITTSeed
 * Signature: (Lorg/jnetpcap/nio/JBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc32CCITTSeed
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    crc32IEEE802
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_crc32IEEE802
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    icmp
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_icmp
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    inChecksum
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_inChecksum
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    inChecksumShouldBe
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_inChecksumShouldBe
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    pseudoTcp
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_pseudoTcp
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    pseudoUdp
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_pseudoUdp
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_util_checksum_Checksum
 * Method:    sctp
 * Signature: (Lorg/jnetpcap/nio/JBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_checksum_Checksum_sctp
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
