/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JMemoryPacket_JMemoryHeader */

#ifndef _Included_org_jnetpcap_packet_JMemoryPacket_JMemoryHeader
#define _Included_org_jnetpcap_packet_JMemoryPacket_JMemoryHeader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
