/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_JPacketSupport_Entry */

#ifndef _Included_org_jnetpcap_util_JPacketSupport_Entry
#define _Included_org_jnetpcap_util_JPacketSupport_Entry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
