/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_JBufferHandler */

#ifndef _Included_org_jnetpcap_JBufferHandler
#define _Included_org_jnetpcap_JBufferHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
