/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JBufferInputStream */

#ifndef _Included_org_jnetpcap_nio_JBufferInputStream
#define _Included_org_jnetpcap_nio_JBufferInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_nio_JBufferInputStream_MAX_SKIP_BUFFER_SIZE
#define org_jnetpcap_nio_JBufferInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
