/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_protocol_JProtocol_Suite */

#ifndef _Included_org_jnetpcap_protocol_JProtocol_Suite
#define _Included_org_jnetpcap_protocol_JProtocol_Suite
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
