/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JHeaderMap */

#ifndef _Included_org_jnetpcap_packet_JHeaderMap
#define _Included_org_jnetpcap_packet_JHeaderMap
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JHeaderMap_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JHeaderMap_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_packet_JHeaderMap_BYTE
#define org_jnetpcap_packet_JHeaderMap_BYTE 8L
#undef org_jnetpcap_packet_JHeaderMap_MAX_HEADERS
#define org_jnetpcap_packet_JHeaderMap_MAX_HEADERS 64L
#ifdef __cplusplus
}
#endif
#endif
