/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_Link */

#ifndef _Included_org_jnetpcap_nio_Link
#define _Included_org_jnetpcap_nio_Link
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
