/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_annotate_BindingVariable */

#ifndef _Included_org_jnetpcap_packet_annotate_BindingVariable
#define _Included_org_jnetpcap_packet_annotate_BindingVariable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
