/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JMemoryPool */

#ifndef _Included_org_jnetpcap_nio_JMemoryPool
#define _Included_org_jnetpcap_nio_JMemoryPool
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_nio_JMemoryPool_DEFAULT_BLOCK_SIZE
#define org_jnetpcap_nio_JMemoryPool_DEFAULT_BLOCK_SIZE 32768L
#ifdef __cplusplus
}
#endif
#endif
