/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_Debug */

#ifndef _Included_org_jnetpcap_util_Debug
#define _Included_org_jnetpcap_util_Debug
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_util_Debug_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_util_Debug_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
/*
 * Class:     org_jnetpcap_util_Debug
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_Debug_sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_util_Debug
 * Method:    setLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_util_Debug_setLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jnetpcap_util_Debug
 * Method:    getLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_util_Debug_getLevel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
