/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapIf */

#ifndef _Included_org_jnetpcap_PcapIf
#define _Included_org_jnetpcap_PcapIf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_PcapIf
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapIf_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
