/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_JThreadLocal */

#ifndef _Included_org_jnetpcap_util_JThreadLocal
#define _Included_org_jnetpcap_util_JThreadLocal
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_util_JThreadLocal_HASH_INCREMENT
#define org_jnetpcap_util_JThreadLocal_HASH_INCREMENT 1640531527L
#ifdef __cplusplus
}
#endif
#endif
