/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_structure_AnnotatedFieldMethod_LongFunction */

#ifndef _Included_org_jnetpcap_packet_structure_AnnotatedFieldMethod_LongFunction
#define _Included_org_jnetpcap_packet_structure_AnnotatedFieldMethod_LongFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
