/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_RegistryException */

#ifndef _Included_org_jnetpcap_packet_RegistryException
#define _Included_org_jnetpcap_packet_RegistryException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_RegistryException_serialVersionUID
#define org_jnetpcap_packet_RegistryException_serialVersionUID -3042686055658047285LL
#undef org_jnetpcap_packet_RegistryException_serialVersionUID
#define org_jnetpcap_packet_RegistryException_serialVersionUID -3387516993124229948LL
#undef org_jnetpcap_packet_RegistryException_serialVersionUID
#define org_jnetpcap_packet_RegistryException_serialVersionUID 2093913023976126160LL
#ifdef __cplusplus
}
#endif
#endif
