/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JPacket */

#ifndef _Included_org_jnetpcap_packet_JPacket
#define _Included_org_jnetpcap_packet_JPacket
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JPacket_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JPacket_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_packet_JPacket_DEFAULT_STATE_HEADER_COUNT
#define org_jnetpcap_packet_JPacket_DEFAULT_STATE_HEADER_COUNT 20L
#ifdef __cplusplus
}
#endif
#endif
