/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_IncompatiblePeer */

#ifndef _Included_org_jnetpcap_IncompatiblePeer
#define _Included_org_jnetpcap_IncompatiblePeer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_IncompatiblePeer_serialVersionUID
#define org_jnetpcap_IncompatiblePeer_serialVersionUID -3042686055658047285LL
#undef org_jnetpcap_IncompatiblePeer_serialVersionUID
#define org_jnetpcap_IncompatiblePeer_serialVersionUID -3387516993124229948LL
#undef org_jnetpcap_IncompatiblePeer_serialVersionUID
#define org_jnetpcap_IncompatiblePeer_serialVersionUID 9081938128324891646LL
#ifdef __cplusplus
}
#endif
#endif
