/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_Units */

#ifndef _Included_org_jnetpcap_util_Units
#define _Included_org_jnetpcap_util_Units
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_util_Units_TEBIBYTE
#define org_jnetpcap_util_Units_TEBIBYTE 1099511627776LL
#undef org_jnetpcap_util_Units_GIGIBYTE
#define org_jnetpcap_util_Units_GIGIBYTE 1073741824L
#undef org_jnetpcap_util_Units_MEBIBYTE
#define org_jnetpcap_util_Units_MEBIBYTE 1048576L
#undef org_jnetpcap_util_Units_KIBIBYTE
#define org_jnetpcap_util_Units_KIBIBYTE 1024L
#undef org_jnetpcap_util_Units_TERABYTE
#define org_jnetpcap_util_Units_TERABYTE 1000000000000LL
#undef org_jnetpcap_util_Units_GIGABYTE
#define org_jnetpcap_util_Units_GIGABYTE 1000000000L
#undef org_jnetpcap_util_Units_MEGABYTE
#define org_jnetpcap_util_Units_MEGABYTE 1000000L
#undef org_jnetpcap_util_Units_KILOBYTE
#define org_jnetpcap_util_Units_KILOBYTE 1000L
#ifdef __cplusplus
}
#endif
#endif
