/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JBuffer */

#ifndef _Included_org_jnetpcap_nio_JBuffer
#define _Included_org_jnetpcap_nio_JBuffer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_nio_JBuffer_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_nio_JBuffer_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_initIds
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getByte0
 * Signature: (JI)B
 */
JNIEXPORT jbyte JNICALL Java_org_jnetpcap_nio_JBuffer_getByte0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getByteArray0
 * Signature: (JI[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jnetpcap_nio_JBuffer_getByteArray0
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getDouble0
 * Signature: (JZI)D
 */
JNIEXPORT jdouble JNICALL Java_org_jnetpcap_nio_JBuffer_getDouble0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getFloat0
 * Signature: (JZI)F
 */
JNIEXPORT jfloat JNICALL Java_org_jnetpcap_nio_JBuffer_getFloat0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getInt0
 * Signature: (JZI)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_nio_JBuffer_getInt0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getLong0
 * Signature: (JZI)J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_nio_JBuffer_getLong0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getShort0
 * Signature: (JZI)S
 */
JNIEXPORT jshort JNICALL Java_org_jnetpcap_nio_JBuffer_getShort0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getUByte0
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_nio_JBuffer_getUByte0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getUInt0
 * Signature: (JZI)J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_nio_JBuffer_getUInt0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    getUShort0
 * Signature: (JZI)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_nio_JBuffer_getUShort0
  (JNIEnv *, jclass, jlong, jboolean, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setByte0
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setByte0
  (JNIEnv *, jclass, jlong, jint, jbyte);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setByteArray0
 * Signature: (JI[BI)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setByteArray0
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setDouble0
 * Signature: (JZID)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setDouble0
  (JNIEnv *, jclass, jlong, jboolean, jint, jdouble);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setFloat0
 * Signature: (JZIF)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setFloat0
  (JNIEnv *, jclass, jlong, jboolean, jint, jfloat);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setInt0
 * Signature: (JZII)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setInt0
  (JNIEnv *, jclass, jlong, jboolean, jint, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setLong0
 * Signature: (JZIJ)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setLong0
  (JNIEnv *, jclass, jlong, jboolean, jint, jlong);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setShort0
 * Signature: (JZIS)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setShort0
  (JNIEnv *, jclass, jlong, jboolean, jint, jshort);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setUByte0
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setUByte0
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setUInt0
 * Signature: (JZIJ)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setUInt0
  (JNIEnv *, jclass, jlong, jboolean, jint, jlong);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setUShort0
 * Signature: (JZII)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setUShort0
  (JNIEnv *, jclass, jlong, jboolean, jint, jint);

/*
 * Class:     org_jnetpcap_nio_JBuffer
 * Method:    setByteBuffer
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JBuffer_setByteBuffer
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
