/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_Pcap_Direction */

#ifndef _Included_org_jnetpcap_Pcap_Direction
#define _Included_org_jnetpcap_Pcap_Direction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
