/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_PcapPacketArrayList */

#ifndef _Included_org_jnetpcap_util_PcapPacketArrayList
#define _Included_org_jnetpcap_util_PcapPacketArrayList
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_util_PcapPacketArrayList_serialVersionUID
#define org_jnetpcap_util_PcapPacketArrayList_serialVersionUID -6379668946303974430LL
#ifdef __cplusplus
}
#endif
#endif
