/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_format_JFormatter_Priority */

#ifndef _Included_org_jnetpcap_packet_format_JFormatter_Priority
#define _Included_org_jnetpcap_packet_format_JFormatter_Priority
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
