/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JNumber_Type */

#ifndef _Included_org_jnetpcap_nio_JNumber_Type
#define _Included_org_jnetpcap_nio_JNumber_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
