/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_winpcap_WinPcapSamp */

#ifndef _Included_org_jnetpcap_winpcap_WinPcapSamp
#define _Included_org_jnetpcap_winpcap_WinPcapSamp
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_winpcap_WinPcapSamp_NO_SAMP
#define org_jnetpcap_winpcap_WinPcapSamp_NO_SAMP 0L
#undef org_jnetpcap_winpcap_WinPcapSamp_ONE_EVERY_N
#define org_jnetpcap_winpcap_WinPcapSamp_ONE_EVERY_N 1L
#undef org_jnetpcap_winpcap_WinPcapSamp_FIRST_AFTER_N_MS
#define org_jnetpcap_winpcap_WinPcapSamp_FIRST_AFTER_N_MS 2L
/*
 * Class:     org_jnetpcap_winpcap_WinPcapSamp
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_winpcap_WinPcapSamp_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_winpcap_WinPcapSamp
 * Method:    getMethod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_winpcap_WinPcapSamp_getMethod
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_winpcap_WinPcapSamp
 * Method:    setMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_winpcap_WinPcapSamp_setMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jnetpcap_winpcap_WinPcapSamp
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_winpcap_WinPcapSamp_getValue
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_winpcap_WinPcapSamp
 * Method:    setValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_winpcap_WinPcapSamp_setValue
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
