/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JNumber */

#ifndef _Included_org_jnetpcap_nio_JNumber
#define _Included_org_jnetpcap_nio_JNumber
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_nio_JNumber_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_nio_JNumber_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_nio_JNumber_BYTE_ORDINAL
#define org_jnetpcap_nio_JNumber_BYTE_ORDINAL 0L
#undef org_jnetpcap_nio_JNumber_CHAR_ORDINAL
#define org_jnetpcap_nio_JNumber_CHAR_ORDINAL 1L
#undef org_jnetpcap_nio_JNumber_INT_ORDINAL
#define org_jnetpcap_nio_JNumber_INT_ORDINAL 2L
#undef org_jnetpcap_nio_JNumber_SHORT_ORDINAL
#define org_jnetpcap_nio_JNumber_SHORT_ORDINAL 3L
#undef org_jnetpcap_nio_JNumber_LONG_ORDINAL
#define org_jnetpcap_nio_JNumber_LONG_ORDINAL 4L
#undef org_jnetpcap_nio_JNumber_LONG_LONG_ORDINAL
#define org_jnetpcap_nio_JNumber_LONG_LONG_ORDINAL 5L
#undef org_jnetpcap_nio_JNumber_FLOAT_ORDINAL
#define org_jnetpcap_nio_JNumber_FLOAT_ORDINAL 6L
#undef org_jnetpcap_nio_JNumber_DOUBLE_ORDINAL
#define org_jnetpcap_nio_JNumber_DOUBLE_ORDINAL 7L
#undef org_jnetpcap_nio_JNumber_MAX_SIZE_ORDINAL
#define org_jnetpcap_nio_JNumber_MAX_SIZE_ORDINAL 8L
/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    sizeof
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_nio_JNumber_sizeof
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    intValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_nio_JNumber_intValue__
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    intValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JNumber_intValue__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    byteValue
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_jnetpcap_nio_JNumber_byteValue__
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    byteValue
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JNumber_byteValue__B
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    shortValue
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_org_jnetpcap_nio_JNumber_shortValue__
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    shortValue
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JNumber_shortValue__S
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    longValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_nio_JNumber_longValue__
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    longValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JNumber_longValue__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    floatValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_jnetpcap_nio_JNumber_floatValue__
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    floatValue
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JNumber_floatValue__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    doubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_jnetpcap_nio_JNumber_doubleValue__
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_nio_JNumber
 * Method:    doubleValue
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JNumber_doubleValue__D
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
