/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JBinding */

#ifndef _Included_org_jnetpcap_packet_JBinding
#define _Included_org_jnetpcap_packet_JBinding
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JBinding_NULL_ID
#define org_jnetpcap_packet_JBinding_NULL_ID -2L
#ifdef __cplusplus
}
#endif
#endif
