/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_structure_AnnotatedScannerMethod */

#ifndef _Included_org_jnetpcap_packet_structure_AnnotatedScannerMethod
#define _Included_org_jnetpcap_packet_structure_AnnotatedScannerMethod
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
