/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapPktBuffer */

#ifndef _Included_org_jnetpcap_PcapPktBuffer
#define _Included_org_jnetpcap_PcapPktBuffer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
