/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_AbstractBinding */

#ifndef _Included_org_jnetpcap_packet_AbstractBinding
#define _Included_org_jnetpcap_packet_AbstractBinding
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
