/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapHandler */

#ifndef _Included_org_jnetpcap_PcapHandler
#define _Included_org_jnetpcap_PcapHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
