/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_format_TextFormatter */

#ifndef _Included_org_jnetpcap_packet_format_TextFormatter
#define _Included_org_jnetpcap_packet_format_TextFormatter
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_format_TextFormatter_COL1
#define org_jnetpcap_packet_format_TextFormatter_COL1 40L
#ifdef __cplusplus
}
#endif
#endif
