/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_Length */

#ifndef _Included_org_jnetpcap_util_Length
#define _Included_org_jnetpcap_util_Length
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
