/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_Disposable */

#ifndef _Included_org_jnetpcap_nio_Disposable
#define _Included_org_jnetpcap_nio_Disposable
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
