/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JHeader_State */

#ifndef _Included_org_jnetpcap_packet_JHeader_State
#define _Included_org_jnetpcap_packet_JHeader_State
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JHeader_State_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JHeader_State_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_packet_JHeader_State_FLAG_CRC_INVALID
#define org_jnetpcap_packet_JHeader_State_FLAG_CRC_INVALID 128L
#undef org_jnetpcap_packet_JHeader_State_FLAG_CRC_PERFORMED
#define org_jnetpcap_packet_JHeader_State_FLAG_CRC_PERFORMED 64L
#undef org_jnetpcap_packet_JHeader_State_FLAG_GAP_TRUNCATED
#define org_jnetpcap_packet_JHeader_State_FLAG_GAP_TRUNCATED 8L
#undef org_jnetpcap_packet_JHeader_State_FLAG_HEADER_TRUNCATED
#define org_jnetpcap_packet_JHeader_State_FLAG_HEADER_TRUNCATED 2L
#undef org_jnetpcap_packet_JHeader_State_FLAG_HEURISTIC_BINDING
#define org_jnetpcap_packet_JHeader_State_FLAG_HEURISTIC_BINDING 32L
#undef org_jnetpcap_packet_JHeader_State_FLAG_PAYLOAD_TRUNCATED
#define org_jnetpcap_packet_JHeader_State_FLAG_PAYLOAD_TRUNCATED 4L
#undef org_jnetpcap_packet_JHeader_State_FLAG_POSTFIX_TRUNCATED
#define org_jnetpcap_packet_JHeader_State_FLAG_POSTFIX_TRUNCATED 16L
#undef org_jnetpcap_packet_JHeader_State_FLAG_PREFIX_TRUNCATED
#define org_jnetpcap_packet_JHeader_State_FLAG_PREFIX_TRUNCATED 1L
#undef org_jnetpcap_packet_JHeader_State_FLAG_HEADER_FRAGMENTED
#define org_jnetpcap_packet_JHeader_State_FLAG_HEADER_FRAGMENTED 256L
#undef org_jnetpcap_packet_JHeader_State_FLAG_FIELDS_DISSECTED
#define org_jnetpcap_packet_JHeader_State_FLAG_FIELDS_DISSECTED 512L
#undef org_jnetpcap_packet_JHeader_State_FLAG_SUBHEADERS_DISSECTED
#define org_jnetpcap_packet_JHeader_State_FLAG_SUBHEADERS_DISSECTED 1024L
#undef org_jnetpcap_packet_JHeader_State_FLAG_IGNORE_BOUNDS
#define org_jnetpcap_packet_JHeader_State_FLAG_IGNORE_BOUNDS 2048L
/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getFlags
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getGap
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getGap
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getId
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getLength
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getOffset
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getPayload
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getPayload
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getPostfix
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getPostfix
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    getPrefix
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_00024State_getPrefix
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_packet_JHeader_State
 * Method:    setFlags
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JHeader_00024State_setFlags
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
