/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JMemoryReference */

#ifndef _Included_org_jnetpcap_nio_JMemoryReference
#define _Included_org_jnetpcap_nio_JMemoryReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_nio_JMemoryReference
 * Method:    disposeNative0
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_nio_JMemoryReference_disposeNative0
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
