/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_PeeringException */

#ifndef _Included_org_jnetpcap_packet_PeeringException
#define _Included_org_jnetpcap_packet_PeeringException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_PeeringException_serialVersionUID
#define org_jnetpcap_packet_PeeringException_serialVersionUID -3042686055658047285LL
#undef org_jnetpcap_packet_PeeringException_serialVersionUID
#define org_jnetpcap_packet_PeeringException_serialVersionUID -3387516993124229948LL
#undef org_jnetpcap_packet_PeeringException_serialVersionUID
#define org_jnetpcap_packet_PeeringException_serialVersionUID 7136151191443182266LL
#ifdef __cplusplus
}
#endif
#endif
