/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_SlidingBuffer */

#ifndef _Included_org_jnetpcap_util_SlidingBuffer
#define _Included_org_jnetpcap_util_SlidingBuffer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
