/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_winpcap_WinPcapRmtAuth */

#ifndef _Included_org_jnetpcap_winpcap_WinPcapRmtAuth
#define _Included_org_jnetpcap_winpcap_WinPcapRmtAuth
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_winpcap_WinPcapRmtAuth_RMT_AUTH_NULL
#define org_jnetpcap_winpcap_WinPcapRmtAuth_RMT_AUTH_NULL 0L
#undef org_jnetpcap_winpcap_WinPcapRmtAuth_RMT_AUTH_PWD
#define org_jnetpcap_winpcap_WinPcapRmtAuth_RMT_AUTH_PWD 1L
/*
 * Class:     org_jnetpcap_winpcap_WinPcapRmtAuth
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_winpcap_WinPcapRmtAuth_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
