/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JHeaderScanner */

#ifndef _Included_org_jnetpcap_packet_JHeaderScanner
#define _Included_org_jnetpcap_packet_JHeaderScanner
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JHeaderScanner_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JHeaderScanner_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
/*
 * Class:     org_jnetpcap_packet_JHeaderScanner
 * Method:    bindNativeScanner
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JHeaderScanner_bindNativeScanner
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_jnetpcap_packet_JHeaderScanner
 * Method:    nativeScan
 * Signature: (Lorg/jnetpcap/packet/JScan;)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_packet_JHeaderScanner_nativeScan
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
