/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapUtils */

#ifndef _Included_org_jnetpcap_PcapUtils
#define _Included_org_jnetpcap_PcapUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_PcapUtils
 * Method:    getHardwareAddress
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jnetpcap_PcapUtils_getHardwareAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jnetpcap_PcapUtils
 * Method:    injectLoop
 * Signature: (IILorg/jnetpcap/packet/PcapPacketHandler;Ljava/lang/Object;Lorg/jnetpcap/packet/PcapPacket;Lorg/jnetpcap/packet/JPacket/State;Lorg/jnetpcap/PcapHeader;Lorg/jnetpcap/packet/JScanner;)I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_PcapUtils_injectLoop
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
