/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_ByteBufferHandler */

#ifndef _Included_org_jnetpcap_ByteBufferHandler
#define _Included_org_jnetpcap_ByteBufferHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
