/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_nio_JStruct */

#ifndef _Included_org_jnetpcap_nio_JStruct
#define _Included_org_jnetpcap_nio_JStruct
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_nio_JStruct_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_nio_JStruct_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#ifdef __cplusplus
}
#endif
#endif
