/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_JEvent */

#ifndef _Included_org_jnetpcap_util_JEvent
#define _Included_org_jnetpcap_util_JEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
