/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_annotate_Analyzer */

#ifndef _Included_org_jnetpcap_packet_annotate_Analyzer
#define _Included_org_jnetpcap_packet_annotate_Analyzer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_annotate_Analyzer_DEFAULT_PRIORITY
#define org_jnetpcap_packet_annotate_Analyzer_DEFAULT_PRIORITY 100L
#ifdef __cplusplus
}
#endif
#endif
