/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JHeader */

#ifndef _Included_org_jnetpcap_packet_JHeader
#define _Included_org_jnetpcap_packet_JHeader
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JHeader_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JHeader_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_packet_JHeader_BYTE
#define org_jnetpcap_packet_JHeader_BYTE 8L
/*
 * Class:     org_jnetpcap_packet_JHeader
 * Method:    sizeof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_packet_JHeader_sizeof
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
