/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_JMappedHeader */

#ifndef _Included_org_jnetpcap_packet_JMappedHeader
#define _Included_org_jnetpcap_packet_JMappedHeader
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_packet_JMappedHeader_MAX_DIRECT_MEMORY_DEFAULT
#define org_jnetpcap_packet_JMappedHeader_MAX_DIRECT_MEMORY_DEFAULT 67108864LL
#undef org_jnetpcap_packet_JMappedHeader_BYTE
#define org_jnetpcap_packet_JMappedHeader_BYTE 8L
#ifdef __cplusplus
}
#endif
#endif
