/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_util_DataUtils */

#ifndef _Included_org_jnetpcap_util_DataUtils
#define _Included_org_jnetpcap_util_DataUtils
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
