/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapDumper */

#ifndef _Included_org_jnetpcap_PcapDumper
#define _Included_org_jnetpcap_PcapDumper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapDumper_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapDumper_close
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    dump0
 * Signature: (JII[BII)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapDumper_dump0
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    dump1
 * Signature: (JIILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapDumper_dump1
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    dump2
 * Signature: (JIILorg/jnetpcap/nio/JBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapDumper_dump2
  (JNIEnv *, jobject, jlong, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jnetpcap_PcapDumper_flush
  (JNIEnv *, jobject);

/*
 * Class:     org_jnetpcap_PcapDumper
 * Method:    ftell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jnetpcap_PcapDumper_ftell
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
