/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_AbstractMessageHeader_MessageType */

#ifndef _Included_org_jnetpcap_packet_AbstractMessageHeader_MessageType
#define _Included_org_jnetpcap_packet_AbstractMessageHeader_MessageType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
