/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_structure_JField_JFieldComp */

#ifndef _Included_org_jnetpcap_packet_structure_JField_JFieldComp
#define _Included_org_jnetpcap_packet_structure_JField_JFieldComp
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
