/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_PcapSockAddr */

#ifndef _Included_org_jnetpcap_PcapSockAddr
#define _Included_org_jnetpcap_PcapSockAddr
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jnetpcap_PcapSockAddr_AF_INET
#define org_jnetpcap_PcapSockAddr_AF_INET 2L
#undef org_jnetpcap_PcapSockAddr_AF_INET6
#define org_jnetpcap_PcapSockAddr_AF_INET6 23L
/*
 * Class:     org_jnetpcap_PcapSockAddr
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jnetpcap_PcapSockAddr_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
