/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jnetpcap_packet_structure_AnnotatedFieldMethod_ObjectFunction */

#ifndef _Included_org_jnetpcap_packet_structure_AnnotatedFieldMethod_ObjectFunction
#define _Included_org_jnetpcap_packet_structure_AnnotatedFieldMethod_ObjectFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
