//
// Created by  YongHaoHu on 15/10/20.
//

#ifndef SNIFF_JNITEST_H
#define SNIFF_JNITEST_H
//
// Created by  YongHaoHu on 15/10/20.
//

#include "jnitest.h"

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yonghaohu_sniff_NdkJniUtils */

#ifndef _Included_com_example_yonghaohu_sniff_NdkJniUtils
#define _Included_com_example_yonghaohu_sniff_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_example_yonghaohu_sniff_NdkJniUtils
* Method:    getCLanguageString
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_example_yonghaohu_sniff_NdkJniUtils_getCLanguageString
        (JNIEnv *, jobject, jstring);

//JNIEXPORT jstring JNICALL Java_com_example_yonghaohu_sniff_NdkJniUtils_getsocket
//        (JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
#endif //SNIFF_JNITEST_H
